.TH EDIT 1 "version 2.0.0"
.SH NAME
edit \- a simple text editor
.SH SYNOPSIS
\fBedit\fP [\fIOPTIONS\fP]... [\fIARGUMENTS\fP]...
.SH DESCRIPTION
edit is a simple text editor inspired by MS-DOS edit.
.SH EDITING
Edit is an interactive mode-less editor. Use F10 to access the menus.
.SH ARGUMENTS
.TP
\fIFILE\fP
The file to open.
.SH OPTIONS
.TP
\fB\-g\fP, \fB\-\-goto\fP \fIFILE:LINE[:CHARACTER]\fP
Open a file at the specified line and character position.
The option applies only to the next file.
Repeat it to open multiple files at specified positions.
.TP
\fB\-h\fP, \fB\-\-help\fP
Print the help message.
.TP
\fB\-v\fP, \fB\-\-version\fP
Print the version number.
.SH COPYRIGHT
Copyright \(co Microsoft Corporation.
.br
Licensed under the MIT License.
.SH SEE ALSO
.UR https://github.com/microsoft/edit
.UE
